### PR TITLE
Upgrade from 0.5.4 -> 0.5.11

### PR DESCRIPTION
**Pull request by TrevorBurnham**
Pulling in the latest tagged upstream release. Changelog: https://github.com/moment/moment-timezone/blob/0.5.11/changelog.md

### CODE REVIEW

**Comment by banderson** [comment]
_Seems_ fine? ¯\_(ツ)_/¯   Are there any tricks other than testing it out and making sure nothing breaks?

**Comment by geekjuice** [comment]
Looking at the changelog, it looks like it _should_ be safe upgrade since it's mostly data updates. Having said that, it doesn't hurt to test locally 😅

**Comment by TrevorBurnham** [comment]
@banderson moment-timezone itself has pretty good unit test coverage, which I've run against this branch. Everything checks out. We also have some tests against this library downstream in I18n. So I'm fairly confident that we won't see any issues; running apps locally against this branch is just an extra precaution.

**Comment by banderson** [comment]
👍 thanks @TrevorBurnham

**Pull request merged**
